"""Tests for the publisher module — pure logic (no live DB)."""

from __future__ import annotations

from unittest.mock import MagicMock

import pytest

from pipeline.publisher import (
    SUBTYPE_TO_CONTENT_TYPE,
    Publisher,
    _parse_sefaria_ref,
)


class TestSefariaRefParsing:
    def test_parses_full_ref_with_halacha(self):
        assert _parse_sefaria_ref("Mishneh Torah, Marriage 2:3") == ("Marriage", 2, 3)

    def test_parses_ref_without_halacha(self):
        assert _parse_sefaria_ref("Mishneh Torah, Marriage 2") == ("Marriage", 2, None)

    def test_parses_multiword_book(self):
        assert _parse_sefaria_ref("Mishneh Torah, The Chosen House 1:5") == (
            "The Chosen House",
            1,
            5,
        )

    def test_handles_missing_work_prefix(self):
        sefer, perek, halacha = _parse_sefaria_ref("Marriage 2:3")
        assert sefer == "Marriage"
        assert perek == 2
        assert halacha == 3

    def test_defaults_perek_to_1_when_missing(self):
        sefer, perek, halacha = _parse_sefaria_ref("SomeBook")
        assert perek == 1
        assert halacha is None


class TestSubtypeMapping:
    def test_illustration_maps_to_conceptual_image(self):
        assert SUBTYPE_TO_CONTENT_TYPE["illustration"] == "conceptual_image"

    def test_infographic_maps_to_infographic(self):
        assert SUBTYPE_TO_CONTENT_TYPE["infographic"] == "infographic"

    def test_chart_maps_to_daily_chart(self):
        assert SUBTYPE_TO_CONTENT_TYPE["chart"] == "daily_chart"

    def test_timeline_maps_to_daily_chart(self):
        assert SUBTYPE_TO_CONTENT_TYPE["timeline"] == "daily_chart"


class TestFrontendURLBuilder:
    def test_uses_explicit_url_env_var(self, monkeypatch):
        monkeypatch.setenv("FRONTEND_DATABASE_URL", "postgresql://explicit/url")
        p = Publisher(pipeline_session=MagicMock())
        assert p.frontend_db_url == "postgresql://explicit/url"

    def test_builds_from_db_env_vars(self, monkeypatch):
        monkeypatch.delenv("FRONTEND_DATABASE_URL", raising=False)
        monkeypatch.setenv("DB_HOST", "dbhost")
        monkeypatch.setenv("DB_PORT", "5555")
        monkeypatch.setenv("DB_NAME", "mydb")
        monkeypatch.setenv("DB_USER", "myuser")
        monkeypatch.setenv("DB_PASS", "mypass")
        p = Publisher(pipeline_session=MagicMock())
        assert p.frontend_db_url == "postgresql://myuser:mypass@dbhost:5555/mydb"

    def test_explicit_constructor_arg_overrides_env(self, monkeypatch):
        monkeypatch.setenv("FRONTEND_DATABASE_URL", "postgresql://env/url")
        p = Publisher(
            pipeline_session=MagicMock(),
            frontend_db_url="postgresql://explicit/arg",
        )
        assert p.frontend_db_url == "postgresql://explicit/arg"


class TestTitleBuilder:
    @pytest.fixture
    def publisher(self):
        return Publisher(
            pipeline_session=MagicMock(),
            frontend_db_url="postgresql://test/db",
        )

    def test_illustration_title_includes_halacha(self, publisher):
        assert publisher._build_title("conceptual_image", "Marriage", 2, 3) == \
            "Illustration — Marriage 2:3"

    def test_illustration_title_without_halacha(self, publisher):
        assert publisher._build_title("conceptual_image", "Marriage", 2, None) == \
            "Illustration — Marriage 2"

    def test_infographic_title(self, publisher):
        assert publisher._build_title("infographic", "Shabbat", 1, None) == \
            "Infographic — Shabbat 1"

    def test_chart_title(self, publisher):
        assert publisher._build_title("daily_chart", "Shabbat", 3, None) == \
            "Chart — Shabbat 3"

    def test_unknown_type_returns_plain_ref(self, publisher):
        assert publisher._build_title("other", "Marriage", 2, 3) == "Marriage 2:3"


class TestContentJSONBuilder:
    @pytest.fixture
    def publisher(self):
        return Publisher(
            pipeline_session=MagicMock(),
            frontend_db_url="postgresql://test/db",
        )

    def test_extracts_visual_focus_from_prompt(self, publisher):
        version = MagicMock()
        version.generation_prompt = "Style prompt\n\nContent context: foo\n\nVisual focus: A Torah scroll on a wooden table"
        version.style_name = "watercolor"

        result = publisher._build_content_json(version, "conceptual_image")
        assert result["caption"] == "A Torah scroll on a wooden table"
        assert result["style"] == "watercolor"

    def test_falls_back_when_no_visual_focus(self, publisher):
        version = MagicMock()
        version.generation_prompt = "no focus line here"
        version.style_name = None

        result = publisher._build_content_json(version, "conceptual_image")
        assert result["caption"] == "Generated by Merkos Rambam pipeline"
        assert result["style"] == ""

    def test_handles_empty_prompt(self, publisher):
        version = MagicMock()
        version.generation_prompt = None
        version.style_name = "oil_painting"

        result = publisher._build_content_json(version, "conceptual_image")
        assert result["caption"] == "Generated by Merkos Rambam pipeline"
        assert result["style"] == "oil_painting"
